@echo off
color 00a
echo realmeUI_1.0_DEBLOATER
pause
echo set adb path in environment variable
echo C:\Users\{username}\AppData\Local\Android\Sdk\tools\platform-tools should be added to PATH under System_Variables.
echo Starting execution....... 
echo ................  
echo ...............  
adb devices
pause
for %%x in (
"com.android.calllogbackup                                     "
"com.android.cellbroadcastreceiver                             "
"com.android.backupconfirm                                     "
"com.android.cellbroadcastreceiver.overlay.common              "
"com.android.email.partnerprovider                             "
"com.android.managedprovisioning                               "
"com.android.providers.partnerbookmarks                        "
"com.android.sharedstoragebackup                               "
"com.android.statementservice                                  "
"com.android.stk                                               "
"com.android.wallpaperbackup                                   "
"com.coloros.pictorial                                         "
"com.coloros.oppomultiapp                                      "
"com.coloros.activation                                        "
"com.coloros.activation.overlay.common                         "
"com.coloros.assistantscreen                                   "
"com.coloros.athena                                            "
"com.coloros.backuprestore                                     "
"com.coloros.backuprestore.remoteservice                       "
"com.coloros.bootreg                                           "
"com.coloros.childrenspace                                     "
"com.coloros.cloud                                             "
"com.coloros.compass2                                          "
"com.coloros.encryption                                        "
"com.coloros.floatassistant                                    "
"com.coloros.gamespace                                         "
"com.coloros.healthcheck                                       "
"com.coloros.lockassistant                                     "
"com.coloros.ocrscanner                                        "
"com.coloros.ocrservice                                        "
"com.coloros.phonemanager                                      "
"com.coloros.phonenoareainquire                                "
"com.coloros.resmonitor                                        "
"com.coloros.sceneservice                                      "
"com.coloros.securepay                                         "
"com.coloros.securitykeyboard                                  "
"com.coloros.smartdrive                                        "
"com.coloros.soundrecorder                                     "
"com.coloros.speechassist                                      "
"com.coloros.translate.engine                                  "
"com.coloros.video                                             "
"com.coloros.wallet                                            "
"com.coloros.weather2                                          "
"com.coloros.widget.smallweather                               "
"com.coloros.wifibackuprestore                                 "
"com.dropboxchmod                                              "
"com.dsi.ant.server                                            "
"com.facebook.appmanager                                       "
"com.facebook.services                                         "
"com.facebook.system                                           "
"com.oppo.usercenter                                           "
"com.ted.number                                                "
"com.oppo.quicksearchbox                                       "
"com.heytap.habit.analysis                                     "
"com.heytap.openid                                             "
"com.heytap.browser                                            "
"com.mediatek.omacp                                            "
"com.mobiletools.systemhelper                                  "
"com.nearme.atlas                                              "
"com.nearme.instant.platform                                   "
"com.nearme.statistics.rom                                     "
"com.nearme.browser                                            "
"com.nearme.themestore                                         "
"com.oppo.ScoreAppMonitor                                      "
"com.oppo.aod                                                  "
"com.oppo.atlas                                                "
"com.oppo.bttestmode                                           "
"com.oppo.criticallog                                          "
"com.oppo.decrypt                                              "
"com.oppo.logkit                                               "
"com.oppo.logkitservice                                        "
"com.oppo.mimosiso                                             "
"com.oppo.music                                                "
"com.oppo.nw                                                   "
"com.oppo.market                                               "
"com.oppo.operationManual                                      "
"com.oppo.oppopowermonitor                                     "
"com.oppo.ovoicemanager                                        "
"com.oppo.partnerbrowsercustomizations                         "
"com.oppo.qualityprotect                                       "
"com.oppo.quicksearchbox                                       "
"com.oppo.rftoolkit                                            "
"com.oppo.sos                                                  "
"com.oppo.startlogkit                                          "
"com.oppo.usageDump                                            "
"com.oppo.webview                                              "
"com.oppo.wifirf                                               "
"com.oppo.wifisniffer                                          "
"com.oppoex.afterservice                                       "
"com.qualcomm.qti.modemtestmode                                "
"com.qualcomm.qti.remoteSimlockAuth                            "
"com.qualcomm.uimremoteclient                                  "
"com.qualcomm.uimremoteserver                                  "
"com.realme.logtool                                            "
"com.realme.securitycheck                                      "
"com.tencent.soter.soterserver                                 "
"com.opera.browser                                             "
"com.coloros.onekeylockscreen                                  "
"com.coloros.gamespaceui                                       "
"com.coloros.wallet                                            "
"com.coloros.securepay                                         "
"com.opera.preinstall                                          "
"com.facebook.katana                                           "
"com.caf.fmradio | FM Radio app                                "
"com.coloros.activation                                        "
"com.coloros.activation.overlay.common                         "
"com.coloros.appmanager | App Manager                          "
"com.coloros.assistantscreen | Smart Assistant                 "
"com.coloros.athena                                            "
"com.coloros.avastofferwall                                    "
"com.coloros.backuprestore                                     "
"com.oppo.quicksearchbox                                       "
"com.heytap.usercenter.overlay                                 "
"com.heytap.usercenter                                         "
"com.heytap.themestore                                         "
"com.heytap.pictorial                                          "
"com.heytap.market | App Market                                "
"com.heytap.habit.analysis                                     "
"com.heytap.datamigration                                      "
"com.heytap.cloud | HeyTap Cloud                               "
"com.heytap.browser | Stock Browser                            "
"com.heytap.mcs | System Messages                              "
"com.heytap.openid                                             "
"com.google.android.youtube | YouTube                          "
"com.google.ar.core                                            "
"com.google.android.tag                                        "
"com.google.android.printservice.recommendation                "
"com.google.android.googlequicksearchbox | Google Search Widget"
"com.google.android.feedback                                   "
"com.google.android.apps.youtube.music | Youtube Music         "
"com.facebook.system                                           "
"com.facebook.services                                         "
"com.facebook.appmanager

) do (
	adb shell pm uninstall --user 0 %%x
)
echo done
pause
